spectraHa: ["/home/james/python_scripts_path/dwd_fit_package/test_data_single/J192359+214103 red_3.dat", "/home/james/python_scripts_path/dwd_fit_package/test_data_single/J192359+214103 red_2.dat", "/home/james/python_scripts_path/dwd_fit_package/test_data_single/J192359+214103 red_1.dat"] # full path desired
spectra_source_type: 'wl_flux_fluxerr' # need to INSERT your source type here. Options are 'wl_flux_fluxerr', 'Xshooter'. Default is 'wl_flux_fluxerr' 
modelHa: [-130,130] # in angstroms
normaliseHa: [[-150,150], [-150,150], [-150,150]]  # in angstroms
cut_Ha_max: [[-200,200], [-200,200], [-200,200]]  # in angstroms
resolutions: [5000, 5000, 5000] # R=lambda/dlambda
refwave: [6562.81, 6562.81, 6562.81]
share_rv: [-1, -1, -1]  # 0 indexed!  needs all shared rvs to be at the end of the line, otherwise won't work properly!!!!!!
starType: ['DA'] # 'DA' or 'DBA
RV_boundaries1: [[-100,100], [-100,100], [-100,100]] # in kms-1
# please note that, where possible, the performance is about 1.4x when identical refwaves have the same normalisation/model/cut.
HJD_Values: [2458359.5157769877, 2458361.3706962164, 2458361.360167127]
forced_teff: [0]   # number or 0
forced_logg: [0]   # number or 0
forced_HoverHe: [0] # only used if DBA is in starType. number or 0
forced_scaling: [False] # False, 'WD' or float. If false, will be added to the mcmc parameters
plot_corner: True # True or False
forced_ephemeris: [False] # expects [False] or [T0, P0]  (in days)
forced_K1: [False] # in kms-1. Options [False], [float], ['Fit']
K1_boundaries: [-300,300] # in kms-1
forced_Vgamma1: [False] # in kms-1. Options [float], ['Fit']
Vgamma1_boundaries: [-100,100] # in kms-1
plot_fit: [False] # [False] or e.g. [0, 1, 4] for spectra 1 2 5
fit_phot_SED: False
RA: "19:23:59.29"  # only used when fit_phot_SED is True. Hexadesimal string or a float. Set to None if not necessary
Dec: "21:41:02.1" # only used when fit_phot_SED is True. Hexadesimal string or a float. Set to None if not necessary
expected_Gmag: 15 # only used when fit_phot_SED is True. Integer/float/None
nwalkers: 25
nburnin: 10
nsteps: 10